export enum HOME_TABS {
  "NOW_PLAYING" = 0,
  "POPULAR" = 1,
  "TOP_RATED" = 2,
  "UPCOMING" = 3,
}

export interface TabType {
  title: string;
  id: number;
}

export const HOME_TABS_ARR: TabType[] = [
  {
    title: "Now Playing",
    id: HOME_TABS.NOW_PLAYING,
  },
  {
    title: "Popular",
    id: HOME_TABS.POPULAR,
  },
  {
    title: "Top Rated",
    id: HOME_TABS.TOP_RATED,
  },
  {
    title: "Upcoming",
    id: HOME_TABS.UPCOMING,
  },
];

export const MOVIE_TEMP_DATA = [
  {
    adult: false,
    backdrop_path: "/pWsD91G2R1Da3AKM3ymr3UoIfRb.jpg",
    genre_ids: [878, 28, 18],
    id: 933131,
    original_language: "ko",
    original_title: "황야",
    overview:
      "After a deadly earthquake turns Seoul into a lawless badland, a fearless huntsman springs into action to rescue a teenager abducted by a mad doctor.",
    popularity: 2214.237,
    poster_path: "/zVMyvNowgbsBAL6O6esWfRpAcOb.jpg",
    release_date: "2024-01-26",
    title: "Badland Hunters",
    video: false,
    vote_average: 6.73,
    vote_count: 421,
  },
  {
    adult: false,
    backdrop_path: "/unvtbkgxh47BewQ8pENvdOdme0r.jpg",
    genre_ids: [28, 18],
    id: 1212073,
    original_language: "de",
    original_title: "60 Minuten",
    overview:
      "Desperate to keep custody of his daughter, a mixed martial arts fighter abandons a big match and races across Berlin to attend her birthday party.",
    popularity: 1421.537,
    poster_path: "/jojfbnIHGsRpodIood3OQoqA45Y.jpg",
    release_date: "2024-01-19",
    title: "Sixty Minutes",
    video: false,
    vote_average: 6.9,
    vote_count: 358,
  },
  {
    adult: false,
    backdrop_path: "/pwGmXVKUgKN13psUjlhC9zBcq1o.jpg",
    genre_ids: [878, 28, 12],
    id: 634492,
    original_language: "en",
    original_title: "Madame Web",
    overview:
      "Forced to confront revelations about her past, paramedic Cassandra Webb forges a relationship with three young women destined for powerful futures...if they can all survive a deadly present.",
    popularity: 1264.699,
    poster_path: "/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg",
    release_date: "2024-02-14",
    title: "Madame Web",
    video: false,
    vote_average: 5.5,
    vote_count: 150,
  },
  {
    adult: false,
    backdrop_path: "/yyFc8Iclt2jxPmLztbP617xXllT.jpg",
    genre_ids: [35, 10751, 14],
    id: 787699,
    original_language: "en",
    original_title: "Wonka",
    overview:
      "Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.",
    popularity: 1341.409,
    poster_path: "/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
    release_date: "2023-12-06",
    title: "Wonka",
    video: false,
    vote_average: 7.195,
    vote_count: 2157,
  },
  {
    adult: false,
    backdrop_path: "/rz8GGX5Id2hCW1KzAIY4xwbQw1w.jpg",
    genre_ids: [28, 35, 80],
    id: 955916,
    original_language: "en",
    original_title: "Lift",
    overview:
      "An international heist crew, led by Cyrus Whitaker, race to lift $500 million in gold from a passenger plane at 40,000 feet.",
    popularity: 1049.137,
    poster_path: "/46sp1Z9b2PPTgCMyA87g9aTLUXi.jpg",
    release_date: "2024-01-10",
    title: "Lift",
    video: false,
    vote_average: 6.6,
    vote_count: 805,
  },
  {
    adult: false,
    backdrop_path: "/ay0PJQZizDXk0pzhoGX4v7K9h7A.jpg",
    genre_ids: [28, 53],
    id: 1214314,
    original_language: "en",
    original_title: "One More Shot",
    overview:
      "Following the attack on the black site in Poland, Navy SEAL Jake Harris is ordered to escort terrorist suspect Amin Mansur to Washington D.C. for interrogation. Before the prisoner transfer process is complete, though, the airport is attacked by a group of heavily armed, well-trained mercenaries.",
    popularity: 1127.297,
    poster_path: "/nQ1BQg4yMdlYSHvHZgwladzy7EF.jpg",
    release_date: "2024-01-12",
    title: "One More Shot",
    video: false,
    vote_average: 6.614,
    vote_count: 149,
  },
  {
    adult: false,
    backdrop_path: "/meyhnvssZOPPjud4F1CjOb4snET.jpg",
    genre_ids: [16, 28, 12, 35, 10751],
    id: 940551,
    original_language: "en",
    original_title: "Migration",
    overview:
      "After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
    popularity: 973.23,
    poster_path: "/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
    release_date: "2023-12-06",
    title: "Migration",
    video: false,
    vote_average: 7.647,
    vote_count: 665,
  },
  {
    adult: false,
    backdrop_path: "/cnqwv5Uz3UW5f086IWbQKr3ksJr.jpg",
    genre_ids: [28, 12, 14],
    id: 572802,
    original_language: "en",
    original_title: "Aquaman and the Lost Kingdom",
    overview:
      "Black Manta seeks revenge on Aquaman for his father's death. Wielding the Black Trident's power, he becomes a formidable foe. To defend Atlantis, Aquaman forges an alliance with his imprisoned brother. They must protect the kingdom.",
    popularity: 852.854,
    poster_path: "/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg",
    release_date: "2023-12-20",
    title: "Aquaman and the Lost Kingdom",
    video: false,
    vote_average: 6.899,
    vote_count: 1704,
  },
  {
    adult: false,
    backdrop_path: "/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg",
    genre_ids: [28, 53, 18],
    id: 866398,
    original_language: "en",
    original_title: "The Beekeeper",
    overview:
      "One man’s campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.",
    popularity: 790.755,
    poster_path: "/A7EByudX0eOzlkQ2FIbogzyazm2.jpg",
    release_date: "2024-01-10",
    title: "The Beekeeper",
    video: false,
    vote_average: 7.261,
    vote_count: 1180,
  },
  {
    adult: false,
    backdrop_path: "/pRmF6VBsRnvWCbLB9P80UvZFMyK.jpg",
    genre_ids: [10749, 35],
    id: 1014590,
    original_language: "en",
    original_title: "Upgraded",
    overview:
      "Ana is an ambitious intern dreaming of a career in the art world while trying to impress her demanding boss Claire. When she's upgraded to first class on a work trip, she meets handsome Will, who mistakes Ana for her boss– a white lie that sets off a glamorous chain of events, romance and opportunity, until her fib threatens to surface.",
    popularity: 971.993,
    poster_path: "/9xn7y63VIpUsIVzSP9fYrqJHyl9.jpg",
    release_date: "2024-02-07",
    title: "Upgraded",
    video: false,
    vote_average: 7.416,
    vote_count: 292,
  },
  {
    adult: false,
    backdrop_path: "/yl2GfeCaPoxChcGyM5p7vYp1CKS.jpg",
    genre_ids: [28, 35, 10749],
    id: 848187,
    original_language: "en",
    original_title: "Role Play",
    overview:
      "Emma has a wonderful husband and two kids in the suburbs of New Jersey – she also has a secret life as an assassin for hire – a secret that her husband David discovers when the couple decide to spice up their marriage with a little role play.",
    popularity: 727.973,
    poster_path: "/7MhXiTmTl16LwXNPbWCmqxj7UxH.jpg",
    release_date: "2024-01-04",
    title: "Role Play",
    video: false,
    vote_average: 6.04,
    vote_count: 353,
  },
  {
    adult: false,
    backdrop_path: "/zLj0peaxy5y2SlC6wNIQ4V0pfqg.jpg",
    genre_ids: [16, 10751, 35, 14],
    id: 1139829,
    original_language: "en",
    original_title: "Orion and the Dark",
    overview:
      "A boy with an active imagination faces his fears on an unforgettable journey through the night with his new friend: a giant, smiling creature named Dark.",
    popularity: 698.175,
    poster_path: "/N2ddXhBX5kqwA9flbm2yqFtX6b.jpg",
    release_date: "2024-02-02",
    title: "Orion and the Dark",
    video: false,
    vote_average: 6.67,
    vote_count: 227,
  },
  {
    adult: false,
    backdrop_path: "/bQS43HSLZzMjZkcHJz4fGc7fNdz.jpg",
    genre_ids: [878, 10749, 35],
    id: 792307,
    original_language: "en",
    original_title: "Poor Things",
    overview:
      "Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.",
    popularity: 636.204,
    poster_path: "/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
    release_date: "2023-12-07",
    title: "Poor Things",
    video: false,
    vote_average: 8.119,
    vote_count: 1221,
  },
  {
    adult: false,
    backdrop_path: "/nTPFkLUARmo1bYHfkfdNpRKgEOs.jpg",
    genre_ids: [35, 10749],
    id: 1072790,
    original_language: "en",
    original_title: "Anyone But You",
    overview:
      "After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.",
    popularity: 611.822,
    poster_path: "/yRt7MGBElkLQOYRvLTT1b3B1rcp.jpg",
    release_date: "2023-12-21",
    title: "Anyone But You",
    video: false,
    vote_average: 6.936,
    vote_count: 448,
  },
  {
    adult: false,
    backdrop_path: "/47SVqaO02doJ06tOmrjiWDkwU3T.jpg",
    genre_ids: [28, 53],
    id: 927107,
    original_language: "en",
    original_title: "The Bricklayer",
    overview:
      "Someone is blackmailing the CIA by assassinating foreign journalists and making it look like the agency is responsible. As the world begins to unite against the U.S., the CIA must lure its most brilliant – and rebellious – operative out of retirement, forcing him to confront his checkered past while unraveling an international conspiracy.",
    popularity: 678.392,
    poster_path: "/36pYugctLa70NmwMEgXTR1G31Kq.jpg",
    release_date: "2023-12-14",
    title: "The Bricklayer",
    video: false,
    vote_average: 6.132,
    vote_count: 117,
  },
  {
    adult: false,
    backdrop_path: "/zIYROrkHJPYB3VTiW1L9QVgaQO.jpg",
    genre_ids: [28, 35],
    id: 897087,
    original_language: "en",
    original_title: "Freelance",
    overview:
      "An ex-special forces operative takes a job to provide security for a journalist as she interviews a dictator, but a military coup breaks out in the middle of the interview, they are forced to escape into the jungle where they must survive.",
    popularity: 640.371,
    poster_path: "/7Bd4EUOqQDKZXA6Od5gkfzRNb0.jpg",
    release_date: "2023-10-05",
    title: "Freelance",
    video: false,
    vote_average: 6.565,
    vote_count: 559,
  },
  {
    adult: false,
    backdrop_path: "/acpFrSmVLnTNAIuHxnZArkC3dwU.jpg",
    genre_ids: [16, 28, 12, 10751, 14],
    id: 598387,
    original_language: "en",
    original_title: "The Tiger's Apprentice",
    overview:
      "After the death of his grandmother, Tom Lee discovers he is part of a long lineage of magical protectors known as the Guardians. With guidance from a mythical tiger named Hu and the other Zodiac animal warriors, Tom trains to take on an evil force that threatens humanity.",
    popularity: 586.958,
    poster_path: "/iiid1xMhoAcW83VJ9LdAqf4Vtbr.jpg",
    release_date: "2024-02-02",
    title: "The Tiger's Apprentice",
    video: false,
    vote_average: 7.243,
    vote_count: 70,
  },
  {
    adult: false,
    backdrop_path: "/1ZSKH5GGFlM8M32K34GMdaNS2Ew.jpg",
    genre_ids: [10402, 18],
    id: 802219,
    original_language: "en",
    original_title: "Bob Marley: One Love",
    overview:
      "Jamaican singer-songwriter Bob Marley overcomes adversity to become the most famous reggae musician in the world.",
    popularity: 453.384,
    poster_path: "/1lQftpEARVVB9op4TaYiIbactzG.jpg",
    release_date: "2024-02-14",
    title: "Bob Marley: One Love",
    video: false,
    vote_average: 6.839,
    vote_count: 56,
  },
  {
    adult: false,
    backdrop_path: "/hIeEpk2w1dnC9ly9ZJwwbunH2Cx.jpg",
    genre_ids: [16, 35, 18, 10751],
    id: 838240,
    original_language: "es",
    original_title: "Robot Dreams",
    overview:
      "Dog lives in Manhattan and he's tired of being alone. One day he decides to build himself a robot, a companion. Their friendship blossoms, until they become inseparable, to the rhythm of 80's NYC. One summer night, Dog, with great sadness, is forced to abandon Robot at the beach. Will they ever meet again?",
    popularity: 336.123,
    poster_path: "/qLtK6DFeuJNuB3THGVDklirhQ8u.jpg",
    release_date: "2023-10-20",
    title: "Robot Dreams",
    video: false,
    vote_average: 7.074,
    vote_count: 54,
  },
  {
    adult: false,
    backdrop_path: "/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    genre_ids: [18, 36],
    id: 872585,
    original_language: "en",
    original_title: "Oppenheimer",
    overview:
      "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    popularity: 480.927,
    poster_path: "/ptpr0kGAckfQkJeJIt8st5dglvd.jpg",
    release_date: "2023-07-19",
    title: "Oppenheimer",
    video: false,
    vote_average: 8.118,
    vote_count: 6721,
  },
];
